name: CI

on:
  push:
    branches: [main]

permissions: {}

jobs:
  pre-commit:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: zsh {0}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo curl -sSL https://packages.osrfoundation.org/gazebo.gpg \
            -o /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] \
            http://packages.osrfoundation.org/gazebo/ubuntu-stable \
            $(lsb_release -cs) main" \
            | sudo tee /etc/apt/sources.list.d/gazebo-stable.list
          sudo apt update && sudo apt install -y --no-install-recommends \
            gz-harmonic \
            cmake \
            doxygen \
            graphviz \
            cppcheck \
            zsh \
            pre-commit \
            clangd
          sudo curl -sSL https://raw.githubusercontent.com/zeromq/cppzmq/v4.10.0/zmq.hpp \
            -o /usr/local/include/zmq.hpp

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew tap osrf/simulation
          brew install gz-harmonic cmake doxygen cppcheck pre-commit

      - name: Set environment (macOS)
        if: runner.os == 'macOS'
        run: |
          {
            echo "OPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3"
            echo "CFLAGS=-I/opt/homebrew/include"
            echo "LDFLAGS=-L/opt/homebrew/lib"
            export CMAKE_PREFIX_PATH="/opt/homebrew/opt/qt@5"
          } >> "$GITHUB_ENV"

      - name: Run pre-commit hooks (Linux)
        if: runner.os == 'Linux'
        env:
          SKIP: check-executables-have-shebangs,docs
        run: pre-commit run --all-files

      - name: Run pre-commit hooks (macOS)
        if: runner.os == 'macOS'
        run: pre-commit run --all-files
